name: kaggle_feedback_ell
channels:
  - fastchan
  - conda-forge
dependencies:
  - python=3.9
  - black
  - notebook
  - jupyter_contrib_nbextensions
  - ipywidgets
  - seaborn
  - pytorch
  - pip
  - pip:
      - ipykernel
      - nbdev
      - -r requirements.txt