# Autogenerated by nbdev

d = { 'settings': { 'branch': 'master',
                'doc_baseurl': '/kaggle_feedback_ell',
                'doc_host': 'https://ohmeow.github.io',
                'git_url': 'https://github.com/ohmeow/kaggle_feedback_ell',
                'lib_path': 'kaggle_comp'},
  'syms': {'kaggle_comp.core': {'kaggle_comp.core.testing': ('core.html#testing', 'kaggle_comp/core.py')}}}