# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/01_config.ipynb.

# %% auto 0
__all__ = ['clean_data_path', 'MODEL_OUTPUT', 'LOG_OUTPUT', 'TRAINING_FILE', 'get_run_id', 'CFG']

# %% ../nbs/01_config.ipynb 3
from pathlib import Path
import pandas as pd
import datetime

from . import utils


# %% ../nbs/01_config.ipynb 5
def get_run_id():
    run_id = str(datetime.datetime.now())[:16].replace(":", "_").replace(" ", "_").replace("-", "_")
    return run_id

# %% ../nbs/01_config.ipynb 8
class CFG:
    subset = 1.0
    n_fold = 5
    fold = [0]
    random_seed = 4321
    #strat_feat = "section_scores"
    preprocess = "basic"
    postprocess = "none"
    augment = "none"
    train_folds = "train_folds.csv"
    experiments = ['blurr_deberta_v3_small']
    grid_params = ['experiments', 'fold']

# %% ../nbs/01_config.ipynb 11
_, _, clean_data_path, MODEL_OUTPUT, LOG_OUTPUT = utils.get_paths()
TRAINING_FILE = Path(clean_data_path) / CFG.train_folds
